
- name: Test TF CLI
  hosts: localhost
  tasks:
    - name: Template main.tf
      ansible.builtin.template:
        src: ./tfc/main.tf.j2
        dest: ./tfc/main.tf
        mode: '0644'
      delegate_to: localhost
    - name: output
      cloud.terraform.terraform_output:
        project_path: './tfc'

    
